[package]
name = "water-sort"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
#bevy = { version = "0.5.0"}
bevy_mod_picking = "0.4"
rand = "0.8.4"
rand_pcg = "0.3.1"
